# Generated by Django 4.2 on 2023-04-09 10:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_alter_toppings_pizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='id',
            field=models.IntegerField(editable=False, primary_key=uuid.uuid4, serialize=False, unique=True),
        ),
    ]
